image:
  repository: "hermaniosan124/desafio-jack"
  tag: "1.3"
  pullPolicy: IfNotPresent

autoscaling:
  enabled: false

replicaCount: 1

ingress:
  enabled: true
  host: "desafiojack.com"

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

configMapData:
  pageTitle: "Portfolio Responsivo"
  logoText: "Portfolio"
  greeting: "Olá"
  mainHeading: "Me Chamo Hermanio Santana"
  jobTitle: "Engenheiro DevOps"
  description: "Estou cursando Engenharia de Software na Universidade Federal do Ceará (UFC) campus de Russas, atualmente no 7° semestre."
  linkedin: "https://linkedin.com/in/hermaniosan"
  whatsapp: "https://wa.me/551199999999"
  github: "https://github.com/hermaniosan124"
  cvLink: "https://example.com/cv.pdf"
  aboutDescription: "Atuo como Engenheiro DevOps com experiência abrangente em Azure DevOps, Kubernetes, Docker, Rancher, Helm e AWS. Especialista em migração de aplicativos .NET 4.8 para .NET 6 e criação de pipelines CI/CD para garantir entrega contínua e integração eficiente de código. Competente na gestão de servidores IIS, automação de tarefas com Shell Script e monitoramento de aplicações usando Elastic e Kibana. Foco na configuração e otimização de ambientes complexos, garantindo soluções robustas e escaláveis."
  backendExperience: "Desenvolvimento em JavaScript, React.js e Node.js. Integração de Bancos de Dados. Implementação de API de Pagamento. Desenvolvimento Orientado para Plataforma de E-commerce. Melhoria Contínua e Funcionalidades Avançadas."
  devOpsExperience: "Tenho experiência com Kubernetes, Docker, AWS, CI/CD e bancos de dados. Curto trabalhar com automação e otimização de infraestrutura na nuvem, sempre buscando deixar tudo mais eficiente e rodando bem."

geral:
  releaseName: "meu-app-desafio-jack"
  namespace: "desafio-jack"
  labels:
    desafio: "jackexperts"